//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB11V2Entities : DbContext
    {
        public DB11V2Entities()
            : base("name=DB11V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseSemester_MTM> CourseSemester_MTM { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeCourseSemester_MTM> EmployeeCourseSemester_MTM { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Timeslot> Timeslots { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<TimetableTimeslot_MTM> TimetableTimeslot_MTM { get; set; }
        public virtual DbSet<WorkingDay> WorkingDays { get; set; }
    
        public virtual ObjectResult<UP_BatchWiseAttendaceReport_Result> UP_BatchWiseAttendaceReport(string batch)
        {
            var batchParameter = batch != null ?
                new ObjectParameter("Batch", batch) :
                new ObjectParameter("Batch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_BatchWiseAttendaceReport_Result>("UP_BatchWiseAttendaceReport", batchParameter);
        }
    
        public virtual ObjectResult<UP_BatchWiseResultReport_Result> UP_BatchWiseResultReport(string batch)
        {
            var batchParameter = batch != null ?
                new ObjectParameter("Batch", batch) :
                new ObjectParameter("Batch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_BatchWiseResultReport_Result>("UP_BatchWiseResultReport", batchParameter);
        }
    
        public virtual ObjectResult<UP_BatchWiseStudentReport_Result> UP_BatchWiseStudentReport(string batch)
        {
            var batchParameter = batch != null ?
                new ObjectParameter("Batch", batch) :
                new ObjectParameter("Batch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_BatchWiseStudentReport_Result>("UP_BatchWiseStudentReport", batchParameter);
        }
    
        public virtual ObjectResult<UP_CourseWiseEmployeeReport_Result> UP_CourseWiseEmployeeReport(string course)
        {
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_CourseWiseEmployeeReport_Result>("UP_CourseWiseEmployeeReport", courseParameter);
        }
    
        public virtual ObjectResult<UP_CourseWiseResultReport_Result> UP_CourseWiseResultReport(string course)
        {
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_CourseWiseResultReport_Result>("UP_CourseWiseResultReport", courseParameter);
        }
    
        public virtual ObjectResult<UP_CourseWiseStudentReport_Result> UP_CourseWiseStudentReport(string course)
        {
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_CourseWiseStudentReport_Result>("UP_CourseWiseStudentReport", courseParameter);
        }
    
        public virtual ObjectResult<UP_SalaryReport_Result> UP_SalaryReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_SalaryReport_Result>("UP_SalaryReport");
        }
    
        public virtual ObjectResult<UP_SemesterWiseAttendaceReport_Result> UP_SemesterWiseAttendaceReport(string semester)
        {
            var semesterParameter = semester != null ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_SemesterWiseAttendaceReport_Result>("UP_SemesterWiseAttendaceReport", semesterParameter);
        }
    
        public virtual ObjectResult<UP_SemesterWiseEmployeeReport_Result> UP_SemesterWiseEmployeeReport(string semester)
        {
            var semesterParameter = semester != null ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_SemesterWiseEmployeeReport_Result>("UP_SemesterWiseEmployeeReport", semesterParameter);
        }
    
        public virtual ObjectResult<UP_StudentFeeReport_Result> UP_StudentFeeReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_StudentFeeReport_Result>("UP_StudentFeeReport");
        }
    }
}
